Fixed PYTHONPATH with ~ expansion plus general corrections
Tilde expansion in PYTHONPATH setting doesn't work because it's quoted:

pi@raspberrypi ~ $ export PYTHONPATH=
pi@raspberrypi ~ $ echo $PYTHONPATH

pi@raspberrypi ~ $ export PYTHONPATH="$PYTHONPATH:~/lib/python"
pi@raspberrypi ~ $ echo $PYTHONPATH
:~/lib/python
pi@raspberrypi ~ $ python lib/python/PyGlow/examples/test.py 
Traceback (most recent call last):
  File "lib/python/PyGlow/examples/test.py", line 15, in <module>
    from PyGlow import PyGlow
ImportError: No module named PyGlow
pi@raspberrypi ~ $ export PYTHONPATH=
pi@raspberrypi ~ $ export PYTHONPATH=$PYTHONPATH:~/lib/python
pi@raspberrypi ~ $ echo $PYTHONPATH
:/home/pi/lib/python
pi@raspberrypi ~ $ python lib/python/PyGlow/examples/test.py 
White: ^CTraceback (most recent call last):
  File "lib/python/PyGlow/examples/test.py", line 20, in <module>
    val = input("White: ")
KeyboardInterrupt

Plus other (very) minor general spelling/grammar corrections, and some more web links.